In [1]:
!wget "https://storage.googleapis.com/kaggle-data-sets/601280/1079953/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250209%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250209T133352Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=93296b8e89b00199d84f909ab7ac6098dee5a544cac94ad0233cef98c9f4191c2abef14f2c7eaf6fc57d512cdeb622cd3761beeae56efb609339ee0cdae5d9e84f4140a4958a0386feebc8575e6241efdfa6202ab7b6f055260d6dcc791e40f1c1d871f3bdfd4cfc27b1b760c644d7ec43cd5bcd0671d5e266d89084396e3fb3ab54dfbc10faf35e4622b4772da9d721e22c9b54de7060ae8180245566c175e444f2e4ece6cfe04aa2d690c8a9f99f1cbf2252a3bd37cae8f4ca4a20a10343f14dbb9ad13ac631ba7f6745d41c9045c3b4cf21121090284c27251870ae2d8b710160b02c250d6f2587016360de1f695bb818661cc84033d2d3b8c1db86a7cc86"

The destination name is too long (767), reducing to 236
--2025-02-09 13:34:10--  https://storage.googleapis.com/kaggle-data-sets/601280/1079953/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20250209%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250209T133352Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=93296b8e89b00199d84f909ab7ac6098dee5a544cac94ad0233cef98c9f4191c2abef14f2c7eaf6fc57d512cdeb622cd3761beeae56efb609339ee0cdae5d9e84f4140a4958a0386feebc8575e6241efdfa6202ab7b6f055260d6dcc791e40f1c1d871f3bdfd4cfc27b1b760c644d7ec43cd5bcd0671d5e266d89084396e3fb3ab54dfbc10faf35e4622b4772da9d721e22c9b54de7060ae8180245566c175e444f2e4ece6cfe04aa2d690c8a9f99f1cbf2252a3bd37cae8f4ca4a20a10343f14dbb9ad13ac631ba7f6745d41c9045c3b4cf21121090284c27251870ae2d8b710160b02c250d6f2587016360de1f695bb818661cc84033d2d3b8c1db86a7cc86
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.31.207, 14

In [2]:
!unzip cancer.zip

Streaming output truncated to the last 5000 lines.
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc10.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc100.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1000.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1001.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1002.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1003.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1004.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1005.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1006.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1007.jpeg  
  inflating: lung_colon_image_set/lung_image_sets/lung_scc/lungscc1008.jpeg  
  inflating: lung_c

In [1]:
from typing import List, Dict, Any
import pandas as pd
import numpy as np
import os

In [4]:
train_df = pd.read_csv(os.path.join('data', "train.csv"))
train_df

FileNotFoundError: [Errno 2] No such file or directory: 'data/train.csv'

In [5]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

train_df = train_df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin']).dropna()
train_df["Sex"] = LabelEncoder().fit_transform(train_df["Sex"])
train_df["Embarked"] = LabelEncoder().fit_transform(train_df["Embarked"])
train_df['Age'] = StandardScaler().fit_transform(train_df['Age'].values.reshape(-1, 1))
train_df['bias'] = np.ones(train_df.shape[0])

NameError: name 'train_df' is not defined

In [ ]:
train_df

Survived  Pclass  Sex       Age  SibSp  Parch  Embarked  bias
0           0       3    1 -0.527669      1      0         2   1.0
1           1       1    0  0.577094      1      0         0   1.0
2           1       3    0 -0.251478      0      0         2   1.0
3           1       1    0  0.369951      1      0         2   1.0
4           0       3    1  0.369951      0      0         2   1.0
..        ...     ...  ...       ...    ...    ...       ...   ...
885         0       3    0  0.646142      0      5         1   1.0
886         0       2    1 -0.182430      0      0         2   1.0
887         1       1    0 -0.734812      0      0         2   1.0
889         1       1    1 -0.251478      0      0         0   1.0
890         0       3    1  0.162808      0      0         1   1.0

[712 rows x 8 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X = train_df.drop(columns=['Survived'])
y = train_df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.15, random_state=69)

In [2]:
import torch
import numpy as np

In [ ]:
X = np.array([1])
Y = np.array([0])
Z = X + Y
X ,Y , Z

(array([1]), array([0]), array([1]))

# Mnist

In [3]:
print('Penis')

Penis


In [2]:
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor

In [ ]:
transform = ToTensor()
mnist_ds = MNIST(root = 'data' ,download=True, transform=transform)
train_ds, val_ds = torch.utils.data.random_split(mnist_ds, [0.85, 0.15])

image, label = train_ds[0]


Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 9.91M/9.91M [00:02<00:00, 4.39MB/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 28.9k/28.9k [00:00<00:00, 63.1kB/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 1.65M/1.65M [00:01<00:00, 1.24MB/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████| 4.54k/4.54k [00:00<00:00, 8.81MB/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [ ]:
image

In [ ]:
train_data_loader = DataLoader(train_ds, batch_size=256, shuffle=True)
val_data_loader = DataLoader(val_ds, batch_size=256, shuffle=False)

# Mnist

In [ ]:
#Model
class MnistModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(28*28, 512)
        self.linear2 = torch.nn.Linear(512, 128)
        self.linear3 = torch.nn.Linear(128, 32)
        self.linear4 = torch.nn.Linear(32, 10)

    def forward(self, a):
        a = torch.relu(self.linear1(a))
        a = torch.relu(self.linear2(a))
        a = torch.relu(self.linear3(a))
        a = torch.sigmoid(self.linear4(a))
        return a

# Training Loop
# Loss, Optimizer, epochs, learning rate, seed

torch.manual_seed(69)
model = MnistModel().cuda()
learning_rate = 0.01
epochs = 10
loss = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


In [ ]:
# def accuracy_with_thresholding_mnist(y_true, y_pred, threshold = 0.5):
#     y_pred = (y_pred > 0.5).int() # Thresholding
#     anded = torch.logical_and(y_pred, y_val) # Element wise AND operation (checking both y_pred and y_true are the same value)
#     sum_accurate = torch.sum(anded).float() # Get the number of times y_pred and y_true agreed
#     sum_accurate /= len(y_pred) # Calculate accuracy for the batch and return it
#     return sum_accurate
def accuracy_no_one_hot(y_pred,y_true):
    _, predicted = y_pred.max(2)
    total = y_true.size(0)
    correct = predicted.eq(y_true).sum().item()
    return correct/total

In [ ]:
from torch.nn.functional import one_hot
max_accuracy = 0
for i in range(epochs):
    for idx, (x_batch, y_batch) in enumerate (train_data_loader):
        y_batch = y_batch.reshape(-1, 1)
        optimizer.zero_grad()
        y_pred = model(x_batch.reshape(-1, 1, 784).cuda())
        loss_value = loss(y_pred.cpu(), one_hot(y_batch, 10).float())
        loss_value.backward()
        optimizer.step()
        if idx % 20 == 0:
            val_loss = 0
            val_accuracy = 0
            for x_val, y_val in val_data_loader:
                y_pred = model(x_val.reshape(-1, 1, 784).cuda())
                y_val = y_val.reshape(-1, 1)
                val_loss += loss(y_pred.cpu(), one_hot(y_val, 10).float())
                val_accuracy += accuracy_no_one_hot(y_pred.cpu(), y_val.float())
            val_accuracy /= len(val_data_loader)
            val_loss /= len(val_data_loader)

            if val_accuracy > max_accuracy:
                max_accuracy = val_accuracy

            print(f"Epoch {i} - Training Loss: {loss_value.item()}, Validation Loss: {val_loss.item()}, Validation Accuracy: {val_accuracy}")

print(loss_value)
# Using the wrong accuract_with_thresholding function

In [ ]:
x_batch.shape

torch.Size([56, 1, 28, 28])

In [ ]:
one_hot(y_batch).shape

torch.Size([256, 10])

In [ ]:
y_batch.shape

torch.Size([256])

In [ ]:
y_val.shape

torch.Size([40, 1, 10])

In [ ]:
y_pred.shape

torch.Size([40, 1, 10])

In [ ]:
y_pred

In [ ]:
y_val

In [ ]:
y_pred = (y_pred > 0.5).int()

In [ ]:
y_pred

In [ ]:
anded = torch.logical_and(y_pred, y_val)
torch.sum(anded)

tensor(40)

In [ ]:
anded.shape

torch.Size([40, 1, 10])

In [ ]:
sum_accurate = torch.sum(anded).float()

In [ ]:
sum_accurate /= len(y_pred)

In [ ]:
sum_accurate

tensor(1.)

In [ ]:
for idx, (x_batch, y_batch) in enumerate (train_data_loader):
        y_batch = y_batch.reshape(-1, 1)
        optimizer.zero_grad()
        y_pred = model(x_batch.reshape(-1, 1, 784).cuda())
        loss_value = loss(y_pred.cpu(), one_hot(y_batch, 10).float())
        loss_value.backward()
        optimizer.step()
        if idx % 20 == 0:
            val_loss = 0
            val_accuracy = 0
            for x_val, y_val in val_data_loader:
                y_pred = model(x_val.reshape(-1, 1, 784).cuda())
                y_val = y_val.reshape(-1, 1)
                val_loss = loss(y_pred.cpu(), one_hot(y_val, 10).float())
                val_accuracy = accuracy_no_one_hot(y_pred.cpu(), y_val.float())
            val_accuracy /= len(val_data_loader)
            val_loss /= len(val_data_loader)

            if val_accuracy > max_accuracy:
                max_accuracy = val_accuracy

            print(f"Epoch {i} - Training Loss: {loss_value.item()}, Validation Loss: {val_loss.item()}, Validation Accuracy: {val_accuracy}")
            break

Epoch 1 - Training Loss: 0.010233274661004543, Validation Loss: 0.00016448496899101883, Validation Accuracy: 0.027083333333333334


In [ ]:
y_pred.shape

torch.Size([40, 1, 10])

In [ ]:
y_val.shape

torch.Size([40, 1])

In [ ]:
one_hot(y_val, 10).float().shape

torch.Size([40, 1, 10])

In [ ]:

_, predicted = y_pred.max(2)
total = y_val.size(0)
correct = predicted.cpu().eq(y_val).sum().item()

In [ ]:
predicted

In [ ]:
total

40

In [ ]:
correct

39

In [ ]:
y_val

tensor([[4],
        [9],
        [3],
        [0],
        [8],
        [4],
        [9],
        [7],
        [9],
        [3],
        [7],
        [7],
        [6],
        [7],
        [1],
        [1],
        [0],
        [4],
        [9],
        [6],
        [7],
        [0],
        [3],
        [7],
        [7],
        [5],
        [1],
        [5],
        [3],
        [5],
        [1],
        [4],
        [7],
        [0],
        [8],
        [4],
        [4],
        [3],
        [2],
        [2]])

In [ ]:
y_pred.max(2)[1]

tensor([[4],
        [9],
        [3],
        [0],
        [8],
        [4],
        [9],
        [7],
        [9],
        [3],
        [7],
        [7],
        [6],
        [7],
        [1],
        [1],
        [0],
        [4],
        [9],
        [6],
        [7],
        [0],
        [3],
        [7],
        [7],
        [5],
        [1],
        [5],
        [3],
        [5],
        [1],
        [4],
        [7],
        [0],
        [8],
        [4],
        [9],
        [3],
        [2],
        [2]], device='cuda:0')

In [ ]:
images, labels = next(iter(train_data_loader))
print("images-size:", images.shape)

print("out-size:", labels.shape)


images-size: torch.Size([256, 1, 28, 28])
out-size: torch.Size([256])


In [ ]:
x_batch[0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0745, 0.7098, 0.9059, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.2000, 0.6314, 0.9255, 0.9882, 0.8196, 0.0000,

In [ ]:
x_batch[1]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

# Mnist using CNN

In [3]:
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.functional import one_hot

In [4]:
class CNNMnistModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 5, 3, stride=1, padding=1) # n, 5, 28, 28 where n = batch_size
        self.fc1 = nn.Linear(5 * 28 * 28, 512) # (3920, 512)
        self.fc2 = nn.Linear(512, 128)
        self.fc3 = nn.Linear(128, 10)
        # self.pool = nn.MaxPool2d(2, 2)
        # self.conv2 = nn.Conv2d(6, 16, 5)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = x.reshape(-1, 28*28*5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.sigmoid(self.fc3(x))
        return x
        # x = self.pool(F.relu(self.conv1(x)))
        # x = self.pool(F.relu(self.conv2(x)))
        # x = torch.flatten(x, 1) # flatten all dimensions except batch
        # x = F.relu(self.fc1(x))
        # x = F.relu(self.fc2(x))
        # x = self.fc3(x)
        # return x

In [5]:
torch.manual_seed(69)
model = CNNMnistModel().cuda()
learning_rate = 0.001
epochs = 10
loss = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
def accuracy_no_one_hot(y_pred,y_true):
    _, predicted = y_pred.max(2)
    total = y_true.size(0)
    correct = predicted.eq(y_true).sum().item()
    return correct/total

In [ ]:
max_accuracy = 0
for i in range(epochs):
  for idx, (x_batch, y_batch) in enumerate(train_data_loader):
    # Training loop
    y_batch = y_batch.reshape(-1, 1)
    optimizer.zero_grad()
    y_pred = model(x_batch.reshape(-1, 1, 28, 28).cuda())
    loss_value = loss(y_pred.cpu().reshape(-1, 1, 10), one_hot(y_batch, 10).float())
    loss_value.backward()
    optimizer.step()
    # Validation loop
    if idx % 20 == 0:
      val_loss = 0
      val_accuracy = 0
      for x_val, y_val in val_data_loader:
        y_pred = model(x_val.reshape(-1, 1, 28, 28).cuda())
        y_val = y_val.reshape(-1, 1)
        val_loss += loss(y_pred.cpu().reshape(-1, 1, 10), one_hot(y_val, 10).float())
        val_accuracy += accuracy_no_one_hot(y_pred.cpu().reshape(-1, 1, 10), y_val.float())
      val_accuracy /= len(val_data_loader)
      val_loss /= len(val_data_loader)

      if val_accuracy > max_accuracy:
        max_accuracy = val_accuracy

      print(f"Epoch {i} - Training Loss: {loss_value.item()}, Validation Loss: {val_loss.item()}, Validation Accuracy: {val_accuracy}")

print(loss_value)

Epoch 0 - Training Loss: 0.6930078268051147, Validation Loss: 0.62453293800354, Validation Accuracy: 0.1212673611111111
Epoch 0 - Training Loss: 0.32423144578933716, Validation Loss: 0.31902551651000977, Validation Accuracy: 0.10219184027777778
Epoch 0 - Training Loss: 0.2889266610145569, Validation Loss: 0.28761398792266846, Validation Accuracy: 0.5281032986111112
Epoch 0 - Training Loss: 0.2076440155506134, Validation Loss: 0.20477065443992615, Validation Accuracy: 0.7328993055555555
Epoch 0 - Training Loss: 0.143526092171669, Validation Loss: 0.1279795914888382, Validation Accuracy: 0.8162760416666667
Epoch 0 - Training Loss: 0.11486707627773285, Validation Loss: 0.09807372838258743, Validation Accuracy: 0.8538628472222222
Epoch 0 - Training Loss: 0.07332531362771988, Validation Loss: 0.08025065809488297, Validation Accuracy: 0.8781032986111111
Epoch 0 - Training Loss: 0.08232925832271576, Validation Loss: 0.06836148351430893, Validation Accuracy: 0.9002387152777778
Epoch 0 - Traini

In [ ]:
y_pred.shape

torch.Size([256, 10])

# Carcenoma classification model using CNN

In [6]:
import glob
import pandas as pd

In [7]:
colon_aca = glob.glob("./lung_colon_image_set/colon_image_sets/*/*")

In [8]:
colon_aca

['./lung_colon_image_set/colon_image_sets/colon_aca/colonca4089.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca3330.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca1479.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca1312.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca1710.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca4284.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca1379.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca253.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca2759.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca631.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca3890.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca1691.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca3838.jpeg',
 './lung_colon_image_set/colon_image_sets/colon_aca/colonca242.jpeg',
 './lung_

In [9]:
df = pd.DataFrame(colon_aca, columns = ["path"])

In [10]:
df

path
0     ./lung_colon_image_set/colon_image_sets/colon_...
1     ./lung_colon_image_set/colon_image_sets/colon_...
2     ./lung_colon_image_set/colon_image_sets/colon_...
3     ./lung_colon_image_set/colon_image_sets/colon_...
4     ./lung_colon_image_set/colon_image_sets/colon_...
...                                                 ...
9995  ./lung_colon_image_set/colon_image_sets/colon_...
9996  ./lung_colon_image_set/colon_image_sets/colon_...
9997  ./lung_colon_image_set/colon_image_sets/colon_...
9998  ./lung_colon_image_set/colon_image_sets/colon_...
9999  ./lung_colon_image_set/colon_image_sets/colon_...

[10000 rows x 1 columns]

In [11]:
df2 = df["path"].str.split("/", expand = True)

In [12]:
labels = df2[3]

In [13]:
labels

0       colon_aca
1       colon_aca
2       colon_aca
3       colon_aca
4       colon_aca
          ...    
9995      colon_n
9996      colon_n
9997      colon_n
9998      colon_n
9999      colon_n
Name: 3, Length: 10000, dtype: object

In [14]:
labeled_colon_data = df

In [15]:
labeled_colon_data["labels"] = labels

In [16]:
labeled_colon_data

path     labels
0     ./lung_colon_image_set/colon_image_sets/colon_...  colon_aca
1     ./lung_colon_image_set/colon_image_sets/colon_...  colon_aca
2     ./lung_colon_image_set/colon_image_sets/colon_...  colon_aca
3     ./lung_colon_image_set/colon_image_sets/colon_...  colon_aca
4     ./lung_colon_image_set/colon_image_sets/colon_...  colon_aca
...                                                 ...        ...
9995  ./lung_colon_image_set/colon_image_sets/colon_...    colon_n
9996  ./lung_colon_image_set/colon_image_sets/colon_...    colon_n
9997  ./lung_colon_image_set/colon_image_sets/colon_...    colon_n
9998  ./lung_colon_image_set/colon_image_sets/colon_...    colon_n
9999  ./lung_colon_image_set/colon_image_sets/colon_...    colon_n

[10000 rows x 2 columns]

In [32]:
from torchvision.io import decode_image
from torchvision.transforms import Normalize

In [33]:
class GetCancer(Dataset):
    def __init__(self, df):
      self.images = df
      self.paths = df["path"]
      self.labels = df["labels"]
      u_labels = self.labels.unique()
      uniques_dict = dict()
      for idx,value in enumerate(u_labels):
        uniques_dict[value] = idx
      self.uniques = uniques_dict
    def __len__(self):
      return len(self.images)

    def __getitem__(self, idx):
      label = self.labels[idx]
      standardization = Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
      return (
          standardization(decode_image(self.paths[idx], mode="RGB").float()),
          F.one_hot(torch.tensor(self.uniques[label], dtype=torch.long), 2).float()
      )


In [34]:
got_cancer = GetCancer(labeled_colon_data)
train_ds, val_ds = torch.utils.data.random_split(got_cancer, [0.85, 0.15])

In [35]:
train_data_loader = DataLoader(train_ds, batch_size=256, shuffle=True)
val_data_loader = DataLoader(val_ds, batch_size=256, shuffle=False)

In [36]:
img, label = train_ds[0]

In [37]:
img.shape

torch.Size([3, 768, 768])

In [38]:
class CNNCancerModel(torch.nn.Module):
  def __init__(self):
    super().__init__()
    # Conv layers
    self.conv1 = nn.Conv2d(3, 1, 3, stride=1, padding=1) # Applies 1 3D filters to the data and returns the same size but 1 channel
    self.maxpool1 = nn.MaxPool2d(2)
    self.conv2 = nn.Conv2d(1, 1, 3, stride=1, padding=1) # Applies 1 2D filter to the data and returns the same size again
    self.maxpool2 = nn.MaxPool2d(2)
    self.conv3 = nn.Conv2d(1, 1, 3, stride=1, padding=1) # Applies 1 2D filter to the data and returns the same size again
    self.maxpool3 = nn.MaxPool2d(2)
    # Linear layers
    self.fc1 = nn.Linear(96*96, 512)
    self.fc2 = nn.Linear(512, 128)
    self.fc3 = nn.Linear(128, 32)
    self.fc4 = nn.Linear(32, 2)

  def forward(self, x):
    x = self.conv1(x)
    x = F.relu(self.maxpool1(x))
    x = self.conv2(x)
    x = F.relu(self.maxpool2(x))
    x = self.conv3(x)
    x = F.relu(self.maxpool3(x))
    x = x.reshape(-1, 96*96)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = F.relu(self.fc3(x))
    x = F.sigmoid(self.fc4(x))
    return x


In [1]:
# Set up Hyperparameters
torch.manual_seed(69)
model = CNNCancerModel().cuda()
learning_rate = 0.001
epochs = 10
loss = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

NameError: name 'torch' is not defined

In [40]:
def accuracy_no_one_hot(y_pred, y_true):
  batch_size = y_pred.size(0)
  y_pred = (y_pred > 0.5).int()
  correct_guesses = 0
  for idx, tensor in enumerate(y_pred):
    if torch.equal(tensor, y_true[idx]):
      correct_guesses += 1
  return correct_guesses/batch_size

In [42]:
max_accuracy = 0
for i in range(epochs):
  for idx, (x_batch, y_batch) in enumerate(train_data_loader):
    # Training loop
    model.train()
    optimizer.zero_grad()
    y_pred = model(x_batch.cuda())
    loss_value = loss(y_pred.cpu(), y_batch)
    loss_value.backward()
    optimizer.step()
    # Validation loop
    model.eval()
    with torch.no_grad():
      if idx % 80 == 0:
        val_loss = 0
        val_accuracy = 0
        for x_val, y_val in val_data_loader:
          y_pred = model(x_val.cuda())
          val_loss += loss(y_pred.cpu(), y_val)
          val_accuracy += accuracy_no_one_hot(y_pred.cpu(), y_val.float())
        val_accuracy /= len(val_data_loader)
        val_loss /= len(val_data_loader)

        if val_accuracy > max_accuracy:
          max_accuracy = val_accuracy

        print(f"Epoch {i} - Training Loss: {loss_value.item()}, Validation Loss: {val_loss.item()}, Validation Accuracy: {val_accuracy}")

print(loss_value)

Epoch 0 - Training Loss: 0.024380531162023544, Validation Loss: 2.1112892627716064, Validation Accuracy: 0.6201822916666667
Epoch 1 - Training Loss: 0.027296219021081924, Validation Loss: 2.8771591186523438, Validation Accuracy: 0.6193181818181818
Epoch 2 - Training Loss: 0.02095741219818592, Validation Loss: 3.1044445037841797, Validation Accuracy: 0.6180160984848485
Epoch 3 - Training Loss: 0.006459298077970743, Validation Loss: 4.241309642791748, Validation Accuracy: 0.6242069128787878
Epoch 4 - Training Loss: 0.0033984684851020575, Validation Loss: 4.777762413024902, Validation Accuracy: 0.6274621212121212
Epoch 5 - Training Loss: 0.00207303068600595, Validation Loss: 4.81010103225708, Validation Accuracy: 0.622360321969697
Epoch 6 - Training Loss: 0.003120490349829197, Validation Loss: 6.012404918670654, Validation Accuracy: 0.6141216856060606
Epoch 7 - Training Loss: 0.005442329216748476, Validation Loss: 5.715104579925537, Validation Accuracy: 0.6191051136363637
Epoch 8 - Traini

In [31]:
y_pred

tensor([[0.2405, 0.7198],
        [0.3329, 0.6414],
        [0.4766, 0.5256],
        [0.2160, 0.7404],
        [0.5489, 0.4535],
        [0.2740, 0.6904],
        [0.9802, 0.0219],
        [0.1900, 0.7625],
        [0.2336, 0.7228],
        [0.3031, 0.6671],
        [0.2353, 0.7230],
        [0.2160, 0.7405],
        [0.7160, 0.2928],
        [0.3034, 0.6699],
        [0.3810, 0.6073],
        [0.3855, 0.6024]], device='cuda:0')

In [30]:
y_val.shape

torch.Size([16, 2])