In [1]:
!unzip data.zip

Archive:  data.zip
   creating: data/
  inflating: data/gender_submission.csv  
  inflating: data/names.txt          
  inflating: data/test.csv           
  inflating: data/train.csv          
 extracting: data/__init__.py        


In [2]:
from typing import List, Dict, Any
import pandas as pd
import numpy as np
import os

In [3]:
train_df = pd.read_csv(os.path.join('data', "train.csv"))
train_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

train_df = train_df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin']).dropna()
train_df["Sex"] = LabelEncoder().fit_transform(train_df["Sex"])
train_df["Embarked"] = LabelEncoder().fit_transform(train_df["Embarked"])
train_df['Age'] = StandardScaler().fit_transform(train_df['Age'].values.reshape(-1, 1))
train_df['bias'] = np.ones(train_df.shape[0])

In [5]:
train_df

Survived  Pclass  Sex       Age  SibSp  Parch  Embarked  bias
0           0       3    1 -0.527669      1      0         2   1.0
1           1       1    0  0.577094      1      0         0   1.0
2           1       3    0 -0.251478      0      0         2   1.0
3           1       1    0  0.369951      1      0         2   1.0
4           0       3    1  0.369951      0      0         2   1.0
..        ...     ...  ...       ...    ...    ...       ...   ...
885         0       3    0  0.646142      0      5         1   1.0
886         0       2    1 -0.182430      0      0         2   1.0
887         1       1    0 -0.734812      0      0         2   1.0
889         1       1    1 -0.251478      0      0         0   1.0
890         0       3    1  0.162808      0      0         1   1.0

[712 rows x 8 columns]

In [6]:
from sklearn.model_selection import train_test_split

X = train_df.drop(columns=['Survived'])
y = train_df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.15, random_state=69)

In [9]:
import torch
import numpy as np

In [10]:
X = np.array([1])
Y = np.array([0])
Z = X + Y
X ,Y , Z

(array([1]), array([0]), array([1]))

# Mnist

In [135]:
print('Penis')


Penis


In [2]:
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor

In [3]:
transform = ToTensor()
mnist_ds = MNIST(root = 'data' ,download=True, transform=transform)
train_ds, val_ds = torch.utils.data.random_split(mnist_ds, [0.85, 0.15])

image, label = train_ds[0]


Failed to download (trying next):
<urlopen error [Errno 111] Connection refused>



100%|██████████| 9.91M/9.91M [00:00<00:00, 11.7MB/s]


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 111] Connection refused>



100%|██████████| 28.9k/28.9k [00:00<00:00, 344kB/s]


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 111] Connection refused>



100%|██████████| 1.65M/1.65M [00:00<00:00, 3.19MB/s]


Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Failed to download (trying next):
<urlopen error [Errno 111] Connection refused>



100%|██████████| 4.54k/4.54k [00:00<00:00, 5.33MB/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [25]:
image

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [109]:
train_data_loader = DataLoader(train_ds, batch_size=256, shuffle=True)
val_data_loader = DataLoader(val_ds, batch_size=256, shuffle=False)

# Mnist

In [136]:
#Model
class MnistModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = torch.nn.Linear(28*28, 512)
        self.linear2 = torch.nn.Linear(512, 128)
        self.linear3 = torch.nn.Linear(128, 32)
        self.linear4 = torch.nn.Linear(32, 10)

    def forward(self, a):
        a = torch.relu(self.linear1(a))
        a = torch.relu(self.linear2(a))
        a = torch.relu(self.linear3(a))
        a = torch.sigmoid(self.linear4(a))
        return a

# Training Loop
# Loss, Optimizer, epochs, learning rate, seed

torch.manual_seed(69)
model = MnistModel().cuda()
learning_rate = 0.01
epochs = 10
loss = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


In [137]:
# def accuracy_with_thresholding_mnist(y_true, y_pred, threshold = 0.5):
#     y_pred = (y_pred > 0.5).int() # Thresholding
#     anded = torch.logical_and(y_pred, y_val) # Element wise AND operation (checking both y_pred and y_true are the same value)
#     sum_accurate = torch.sum(anded).float() # Get the number of times y_pred and y_true agreed
#     sum_accurate /= len(y_pred) # Calculate accuracy for the batch and return it
#     return sum_accurate
def accuracy_no_one_hot(y_pred,y_true):
    _, predicted = y_pred.max(2)
    total = y_true.size(0)
    correct = predicted.eq(y_true).sum().item()
    return correct/total

In [ ]:
from torch.nn.functional import one_hot
max_accuracy = 0
for i in range(epochs):
    for idx, (x_batch, y_batch) in enumerate (train_data_loader):
        y_batch = y_batch.reshape(-1, 1)
        optimizer.zero_grad()
        y_pred = model(x_batch.reshape(-1, 1, 784).cuda())
        loss_value = loss(y_pred.cpu(), one_hot(y_batch, 10).float())
        loss_value.backward()
        optimizer.step()
        if idx % 20 == 0:
            val_loss = 0
            val_accuracy = 0
            for x_val, y_val in val_data_loader:
                y_pred = model(x_val.reshape(-1, 1, 784).cuda())
                y_val = y_val.reshape(-1, 1)
                val_loss += loss(y_pred.cpu(), one_hot(y_val, 10).float())
                val_accuracy += accuracy_no_one_hot(y_pred.cpu(), y_val.float())
            val_accuracy /= len(val_data_loader)
            val_loss /= len(val_data_loader)

            if val_accuracy > max_accuracy:
                max_accuracy = val_accuracy

            print(f"Epoch {i} - Training Loss: {loss_value.item()}, Validation Loss: {val_loss.item()}, Validation Accuracy: {val_accuracy}")

print(loss_value)
# Using the wrong accuract_with_thresholding function

In [28]:
x_batch.shape

torch.Size([56, 1, 28, 28])

In [ ]:
one_hot(y_batch).shape

torch.Size([256, 10])

In [ ]:
y_batch.shape

torch.Size([256])

In [ ]:
y_val.shape

torch.Size([40, 1, 10])

In [ ]:
y_pred.shape

torch.Size([40, 1, 10])

In [10]:
y_pred

tensor([[[0.0034, 0.0032, 0.0034,  ..., 0.0034, 0.0031, 0.0089]],

        [[0.0034, 0.0032, 0.0091,  ..., 0.0034, 0.0031, 0.0033]],

        [[0.0034, 0.0032, 0.0091,  ..., 0.0034, 0.0031, 0.0033]],

        ...,

        [[0.0034, 0.0032, 0.0034,  ..., 0.0034, 0.0031, 0.0033]],

        [[0.0034, 0.0032, 0.0034,  ..., 0.0093, 0.0031, 0.0033]],

        [[0.0034, 0.0032, 0.0034,  ..., 0.0034, 0.0086, 0.0089]]],
       device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [ ]:
y_val

In [ ]:
y_pred = (y_pred > 0.5).int()

In [ ]:
y_pred

In [ ]:
anded = torch.logical_and(y_pred, y_val)
torch.sum(anded)

tensor(40)

In [ ]:
anded.shape

torch.Size([40, 1, 10])

In [ ]:
sum_accurate = torch.sum(anded).float()

In [ ]:
sum_accurate /= len(y_pred)

In [ ]:
sum_accurate

tensor(1.)

In [127]:
for idx, (x_batch, y_batch) in enumerate (train_data_loader):
        y_batch = y_batch.reshape(-1, 1)
        optimizer.zero_grad()
        y_pred = model(x_batch.reshape(-1, 1, 784).cuda())
        loss_value = loss(y_pred.cpu(), one_hot(y_batch, 10).float())
        loss_value.backward()
        optimizer.step()
        if idx % 20 == 0:
            val_loss = 0
            val_accuracy = 0
            for x_val, y_val in val_data_loader:
                y_pred = model(x_val.reshape(-1, 1, 784).cuda())
                y_val = y_val.reshape(-1, 1)
                val_loss = loss(y_pred.cpu(), one_hot(y_val, 10).float())
                val_accuracy = accuracy_no_one_hot(y_pred.cpu(), y_val.float())
            val_accuracy /= len(val_data_loader)
            val_loss /= len(val_data_loader)

            if val_accuracy > max_accuracy:
                max_accuracy = val_accuracy

            print(f"Epoch {i} - Training Loss: {loss_value.item()}, Validation Loss: {val_loss.item()}, Validation Accuracy: {val_accuracy}")
            break

Epoch 1 - Training Loss: 0.010233274661004543, Validation Loss: 0.00016448496899101883, Validation Accuracy: 0.027083333333333334


In [128]:
y_pred.shape

torch.Size([40, 1, 10])

In [129]:
y_val.shape

torch.Size([40, 1])

In [130]:
one_hot(y_val, 10).float().shape

torch.Size([40, 1, 10])

In [131]:

_, predicted = y_pred.max(2)
total = y_val.size(0)
correct = predicted.cpu().eq(y_val).sum().item()

In [ ]:
predicted

In [140]:
total

40

In [139]:
correct

39

In [133]:
y_val

tensor([[4],
        [9],
        [3],
        [0],
        [8],
        [4],
        [9],
        [7],
        [9],
        [3],
        [7],
        [7],
        [6],
        [7],
        [1],
        [1],
        [0],
        [4],
        [9],
        [6],
        [7],
        [0],
        [3],
        [7],
        [7],
        [5],
        [1],
        [5],
        [3],
        [5],
        [1],
        [4],
        [7],
        [0],
        [8],
        [4],
        [4],
        [3],
        [2],
        [2]])

In [134]:
y_pred.max(2)[1]

tensor([[4],
        [9],
        [3],
        [0],
        [8],
        [4],
        [9],
        [7],
        [9],
        [3],
        [7],
        [7],
        [6],
        [7],
        [1],
        [1],
        [0],
        [4],
        [9],
        [6],
        [7],
        [0],
        [3],
        [7],
        [7],
        [5],
        [1],
        [5],
        [3],
        [5],
        [1],
        [4],
        [7],
        [0],
        [8],
        [4],
        [9],
        [3],
        [2],
        [2]], device='cuda:0')

In [110]:
images, labels = next(iter(train_data_loader))
print("images-size:", images.shape)

print("out-size:", labels.shape)


images-size: torch.Size([256, 1, 28, 28])
out-size: torch.Size([256])


In [112]:
x_batch[0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0745, 0.7098, 0.9059, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.2000, 0.6314, 0.9255, 0.9882, 0.8196, 0.0000,

In [113]:
x_batch[1]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0745,  0.7098,  0.9059,
           0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000,  0.0000,  0